export enum actionTypes {
  CHARACTERS_REQUEST = 'CHARACTERS_REQUEST',
  CHARACTERS_SUCCESS = 'CHARACTERS_SUCCESS',
  CHARACTERS_FAILURE = 'CHARACTERS_FAILURE',

  CHARACTER_NAME_REQUEST = 'CHARACTER_NAME_REQUEST',
  CHARACTER_NAME_SUCCESS = 'CHARACTER_NAME_SUCCESS',
  CHARACTER_NAME_FAILURE = 'CHARACTER_NAME_FAILURE',

  SET_SHOW_PAGE = 'SET_SHOW_PAGE',

  ADD_FAVORITE = 'ADD_FAVORITE',
  REMOVE_FAVORITE = 'REMOVE_FAVORITE',
};
